[project]
name = "eikonax"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chex>=0.1.86",
    "equinox>=0.11.5",
    "jax>=0.4.31",
    "numpy>=2.1.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.2",
    "ruff>=0.6.4",
]
environments = [
    "sys_platform == 'linux'",
]
