[project]
authors = [{name = "Maximilian Kruse", email = "maximilian.kruse@kit.edu"}]
description = "Add a short description here"
name = "eikonax"
requires-python = ">= 3.12"
version = "0.1.0"
readme = "README.md"
license = {text = "MIT License"}
dependencies = []

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
eikonax = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
jax = ">=0.4.31,<0.5"
chex = ">=0.1.86,<0.2"
equinox = ">=0.11.5,<0.12"
numpy = ">=2.1.1,<3"

[tool.pixi.feature.development.dependencies]
pytest = "*"
ruff = "*"

[tool.pixi.environments]
default = { solve-group = "default" }
development = { features = ["development"], solve-group = "default" }

[tool.ruff]
line-length = 100

[tool.ruff.pydocstyle]
convention = "google"
