name: CI
run-name: Format code with Ruff and run tests with Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install project dependencies 
        if: ${{ steps.setup-uv.outputs.cache-hit != 'true'}}
        run: echo "Cache miss!"
        #run: uv sync --all-extras --dev
  formatting:
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Format code with Ruff
        run: uv run ruff format

