# -- Github Workflow for Continuous Integration ----------------------------------------------------
# Intended to be used on push for PR to main
# This workflow will:
# 1. Format code with Ruff
# 2. Run tests with Pytest
name: CI
run-name: Continuous Integration for Main branch


# -- Trigger Events --------------------------------------------------------------------------------
on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  

# -- Jobs ------------------------------------------------------------------------------------------
jobs:
  # Format codewith Ruff
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      id: checkout-code
      uses: actions/checkout@v4
    - name: Install uv
      id: setup-uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - name: Format code with Ruff
      id: format-ruff
      run: uvx ruff format
  # Run tests with Pytest
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      id: checkout-code
      uses: actions/checkout@v4
    - name: Install uv
      id: setup-uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - name: Install dependencies
      id: install-deps
      run: uv sync --dev
    - name: Run tests with Pytest
      id: run-tests
      run: uv run pytest


