# -- Github Workflow Release Creation --------------------------------------------------------------
# Releases are created when a new tag is pushed to the main branch of the repository
# Version tags require semantic versioning
name: Release
run-name: Create Github release from tagged commit

# -- Trigger Events --------------------------------------------------------------------------------
on:
  workflow_dispatch:
  release:

# -- Jobs ------------------------------------------------------------------------------------------
jobs:
  # Publish to Test-PyPI
  publish-pypi:
    runs-on: ubuntu-latest
    environment: test-pypi
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v4
      - name: Install uv
        id: setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Publish with uv
        id: publish
        run: |
          uv build
          uv publish --publish-url https://test.pypi.org/legacy/ --trusted-publishing always