# -- Github Workflow for Publishing to Index -------------------------------------------------------
# Workflow is triggered when a new release is created
name: Publish
run-name: Publish Python package to indices

# -- Trigger Events --------------------------------------------------------------------------------
on:
  workflow_dispatch:
  release:

# -- Jobs ------------------------------------------------------------------------------------------
jobs:
  # Publish to Test-PyPI
  publish-testpypi:
    runs-on: ubuntu-latest
    environment: test-pypi
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v4
      - name: Install uv
        id: setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Publish with uv
        id: publish
        run: |
          uv build
          uv publish --publish-url https://test.pypi.org/legacy/ --trusted-publishing always