# -- Github Workflow Release Creation --------------------------------------------------------------
# Releases are created when a new tag is pushed to the main branch of the repository
# Version tags require semantic versioning
name: Release
run-name: Create Github release from tagged commit

# -- Trigger Events --------------------------------------------------------------------------------
on:
  workflow_dispatch:
  push:
    tags:
      - v*

# -- Jobs ------------------------------------------------------------------------------------------
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v4
      - name: Create release
        id: create-release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}/CHANGELOG.md
